### ISSUE TITLE
can't display labels and tooltips on some charts like Treemaps

### ISSUE THREAD

**Issue by cannibalox** [guzhongren/logseq-echarts#51]
hey, thanks for the great plugin ! 
I have trouble displaying labels on a Treemap (similar to the Treemap-simple demo from : https://echarts.apache.org/examples/en/editor.html?c=treemap-simple )

here's the render comparison, logseq on the left, e-charts website on the right:
![image](https://user-images.githubusercontent.com/4605693/214214963-17a297d1-536b-4b99-8021-8b1627f3c808.png)

labels are not showing in logseq. not sure if it's a bug or the feature is not implemented yet.

the code for the Treemap, using label attributes
```
option = {

 backgroundColor: '#2c343c',
  title: {
    text: 'My Treemap',
    left: 'center',
    top: 20,
    textStyle: {
      color: '#ccc'
    }
  },
  legend: {
    type: "plain",
    show: true,
  },
  tooltip: {
    show: true,
   trigger: "item"
  },
  series: [
    {
      type: 'treemap',
      sort: false,
      data: [
        {
          name: 'nodeA',
          value: 10,
          children: [
            {
              name: 'nodeAa',
              value: 4
            },
            {
              name: 'nodeAb',
              value: 6
            }
          ]
        },
        {
          name: 'nodeB',
          value: 20,
          children: [
            {
              name: 'nodeBa',
              value: 20,
              children: [
                {
                  name: 'nodeBa1',
                  value: 20
                }
              ]
            }
          ]
        },
        {
          name: 'phi',
          value: 14
        },
        {
          name: 'phi2',
          value: 21
        }
      ],

      label: {
        show: true,
        distance: 2,
        padding: 5,
        position: "inside",
        formatter: '{b}:{@score}',
        color: '#fff',
        fontStyle: 'normal',
        fontWeight: 'normal',
        fontSize: 34
      },
	itemStyle: {
      borderWidth: 2,
      borderColor: "#ff0000",
    },
    tooltip: {
    show: true
   }
  }
  ]
};
```

**Comment by guzhongren** [comment]
Hey, @cannibalox thx for your feedback
I think it is a bug from echarts, this is a demo, and I report this bug to echarts team, need echarts team to confirm and fix

Reported issue: https://github.com/apache/echarts/issues/18205
Bug showcase: https://stackblitz.com/edit/js-pdnjm1?file=index.js

**Comment by cannibalox** [comment]
thank you for the details and for reporting the link upstream. I hope they can fix the issue :)

**Comment by guzhongren** [comment]
Hey, @cannibalox 
this issue has been fixed by echarts org,
you can upgrade this plugin to the latest version(v.14.0),

thanks for your feedback again.
